"""initial migration

Revision ID: ffd9ebd83a37
Revises: 
Create Date: 2026-06-10 21:42:12.660181

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ffd9ebd83a37'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('retailer', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('brand', sa.String(), nullable=True),
    sa.Column('size', sa.String(), nullable=True),
    sa.Column('unit', sa.String(), nullable=True),
    sa.Column('unit_price', sa.Float(), nullable=True),
    sa.Column('loyalty_price', sa.Float(), nullable=True),
    sa.Column('promotion', sa.String(), nullable=True),
    sa.Column('image_url', sa.String(), nullable=True),
    sa.Column('product_url', sa.String(), nullable=True),
    sa.Column('affiliate_url', sa.String(), nullable=True),
    sa.Column('match_confidence', sa.Float(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_products_category'), 'products', ['category'], unique=False)
    op.create_index(op.f('ix_products_id'), 'products', ['id'], unique=False)
    op.create_index(op.f('ix_products_name'), 'products', ['name'], unique=False)
    op.create_index(op.f('ix_products_retailer'), 'products', ['retailer'], unique=False)
    op.create_table('retailer_locations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('country', sa.String(), nullable=True),
    sa.Column('code', sa.String(), nullable=True),
    sa.Column('retailer', sa.String(), nullable=True),
    sa.Column('loyalty_scheme', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_retailer_locations_code'), 'retailer_locations', ['code'], unique=False)
    op.create_index(op.f('ix_retailer_locations_country'), 'retailer_locations', ['country'], unique=False)
    op.create_index(op.f('ix_retailer_locations_id'), 'retailer_locations', ['id'], unique=False)
    op.create_index(op.f('ix_retailer_locations_retailer'), 'retailer_locations', ['retailer'], unique=False)
    op.create_table('affiliate_clicks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('retailer', sa.String(), nullable=False),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('clicked_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_affiliate_clicks_clicked_at'), 'affiliate_clicks', ['clicked_at'], unique=False)
    op.create_index(op.f('ix_affiliate_clicks_id'), 'affiliate_clicks', ['id'], unique=False)
    op.create_index(op.f('ix_affiliate_clicks_retailer'), 'affiliate_clicks', ['retailer'], unique=False)
    op.create_table('price_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('retailer', sa.String(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('loyalty_price', sa.Float(), nullable=True),
    sa.Column('observed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_price_history_id'), 'price_history', ['id'], unique=False)
    op.create_index(op.f('ix_price_history_observed_at'), 'price_history', ['observed_at'], unique=False)
    op.create_index(op.f('ix_price_history_product_id'), 'price_history', ['product_id'], unique=False)
    op.create_index(op.f('ix_price_history_retailer'), 'price_history', ['retailer'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_price_history_retailer'), table_name='price_history')
    op.drop_index(op.f('ix_price_history_product_id'), table_name='price_history')
    op.drop_index(op.f('ix_price_history_observed_at'), table_name='price_history')
    op.drop_index(op.f('ix_price_history_id'), table_name='price_history')
    op.drop_table('price_history')
    op.drop_index(op.f('ix_affiliate_clicks_retailer'), table_name='affiliate_clicks')
    op.drop_index(op.f('ix_affiliate_clicks_id'), table_name='affiliate_clicks')
    op.drop_index(op.f('ix_affiliate_clicks_clicked_at'), table_name='affiliate_clicks')
    op.drop_table('affiliate_clicks')
    op.drop_index(op.f('ix_retailer_locations_retailer'), table_name='retailer_locations')
    op.drop_index(op.f('ix_retailer_locations_id'), table_name='retailer_locations')
    op.drop_index(op.f('ix_retailer_locations_country'), table_name='retailer_locations')
    op.drop_index(op.f('ix_retailer_locations_code'), table_name='retailer_locations')
    op.drop_table('retailer_locations')
    op.drop_index(op.f('ix_products_retailer'), table_name='products')
    op.drop_index(op.f('ix_products_name'), table_name='products')
    op.drop_index(op.f('ix_products_id'), table_name='products')
    op.drop_index(op.f('ix_products_category'), table_name='products')
    op.drop_table('products')
    # ### end Alembic commands ###
